### ISSUE TITLE
Is the ROS functionality tested with catkin_tools?

### ISSUE THREAD

**Issue by ghost** [kyrofa/github-snap-builder-docker#3]
I'm trying to use this setup to create a snap with ROS, but it fails when trying to build the software. The used plugin is catkin_tools. Below I've pasted the output of the error message. The reason seems to be that it tries to find information about the current Linux distribution, but this file doesn't exist within the Docker. Is this a bug, an oversight or something else? The only difference I can see between the build is the usage of multipass, which doesn't happen within the docker.

Traceback (most recent call last):
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 38, in get_distro_info
    csvfile = open('/usr/share/distro-info/%s.csv' % origin.lower())
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/distro-info/debian.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/parts/isaac/install/usr/bin/lsb_release", line 26, in <module>
    import lsb_release
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 57, in <module>
    get_distro_info()
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    csvfile = open('/usr/share/distro-info/debian.csv')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/distro-info/debian.csv'
CMake Error at /build/parts/isaac/install/opt/ros/melodic/share/catkin/cmake/platform/lsb.cmake:8 (string):
  string no output variable specified
Call Stack (most recent call first):
  /build/parts/isaac/install/opt/ros/melodic/share/catkin/cmake/all.cmake:163 (include)
  /build/parts/isaac/install/opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)

Traceback (most recent call last):
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 38, in get_distro_info
    csvfile = open('/usr/share/distro-info/%s.csv' % origin.lower())
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/distro-info/debian.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/parts/isaac/install/usr/bin/lsb_release", line 26, in <module>
    import lsb_release
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 57, in <module>
    get_distro_info()
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    csvfile = open('/usr/share/distro-info/debian.csv')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/distro-info/debian.csv'
Traceback (most recent call last):
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 38, in get_distro_info
    csvfile = open('/usr/share/distro-info/%s.csv' % origin.lower())
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/distro-info/debian.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/parts/isaac/install/usr/bin/lsb_release", line 26, in <module>
    import lsb_release
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 57, in <module>
    get_distro_info()
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    csvfile = open('/usr/share/distro-info/debian.csv')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/distro-info/debian.csv'
Traceback (most recent call last):
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 38, in get_distro_info
    csvfile = open('/usr/share/distro-info/%s.csv' % origin.lower())
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/distro-info/debian.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/parts/isaac/install/usr/bin/lsb_release", line 26, in <module>
    import lsb_release
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 57, in <module>
    get_distro_info()
  File "/build/parts/isaac/install/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    csvfile = open('/usr/share/distro-info/debian.csv')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/distro-info/debian.csv'
CMake Error at /build/parts/isaac/install/opt/ros/melodic/share/catkin/cmake/platform/lsb.cmake:21 (string):
  string no output variable specified
Call Stack (most recent call first):
  /build/parts/isaac/install/opt/ros/melodic/share/catkin/cmake/all.cmake:163 (include)
  /build/parts/isaac/install/opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)

**Comment by kyrofa** [comment]
Wow, I'm so sorry I never responded to this. This is a repo I maintain for a very specific purpose (my snap builder github app) that only I use (I thought) so I have been awful about actually monitoring it for issues logged against it. I suggest using https://forum.snapcraft.io/ in the future, it will have more visibility.

To answer the question in the title of your issue: no. The only place I knew of this image being used was _my_ usage of it, which was to build the Nextcloud snap. I have not put a lot of mileage on it beyond that, and I'm actually no longer using it there either. I have not tried building ROS snaps on it.

That said, this should work fine as long as you're not using build- or stage-snaps. What you've run into is technically [a bug](https://bugs.launchpad.net/snapcraft/+bug/1677002), but one that isn't particularly easy to solve without some significant changes, which are happening for core20 (ROS Noetic and Foxy). The workaround is, as the bug describes, to add `lsb-release` to your build packages.

For example:

```yaml
# ...
parts:
  ros-tutorials:
    plugin: catkin-tools
    source: https://github.com/ros/ros_tutorials.git
    source-branch: melodic-devel
    source-space: roscpp_tutorials/
    build-packages: [lsb-release]  # <- this
# ...
```
